version: '3.9'

services:
  app:
    build:
      context: .
      target: ${APP_TARGET}
    depends_on:
      - mysql
    ports:
      - 80:3000
    restart: always
    develop:
      watch:
      - path: .
        action: sync
        ignore:
          - node_modules/
        target: app

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - db.env
    environment:
      MYSQL_TCP_PORT: 3306
    expose:
      - 3306
    restart: always

  adminer:
    image: adminer
    depends_on:
      - mysql
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    ports:
      - 10000:8080
    restart: always

volumes:
  mysql-data:
